### ISSUE TITLE
Expose the plugin as custom command

### ISSUE THREAD

**Issue by webflo** [drupal-composer/drupal-paranoia#2]
Similar to this PR in drupal-scaffold https://github.com/drupal-composer/drupal-scaffold/pull/61

With this, its not necessary to add "drupal-paranoia" to the scripts section of composer.json

**Comment by jkribeiro** [comment]
PR: https://github.com/drupal-composer/drupal-paranoia/pull/3

**Comment by kmoll** [comment]
I have gone through and reviewed this and it is working sucessfully.  I can confirm that on install/update code is put in app_root and web artifacts in docroot.  I created new images and ran the script manually and it copied items from the app_root to the web_root.

**Comment by jkribeiro** [comment]
great, thanks for your review and testing @kmoll.

Releasing.

**Comment by jkribeiro** [comment]
Released: https://github.com/drupal-composer/drupal-paranoia/releases/tag/1.0.0-alpha2
