### ISSUE TITLE
Support for composer 2

### ISSUE THREAD

**Issue by emilorol** [drupal-composer/drupal-paranoia#21]
Installing plugin with Composer 2 install failed.

```
➜  www.demo-site.com composer require drupal-composer/drupal-paranoia:~1

  [InvalidArgumentException]
  Package drupal-composer/drupal-paranoia at version ~1 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

➜  www.demo-site.com php -v
PHP 7.3.9 (cli) (built: Feb 17 2020 12:46:14) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

➜  www.demo-site.com composer -V
Composer version 2.0.2 2020-10-25 23:03:59
```

### Expected behavior
Instal

### Actual behavior
Error out

### Steps to reproduce
1. Install composer 2
2. Install Drupal 8 or 9 using drupal-composer
3. Apply the fixes to the compose.json file
4. Install drupal paranoia using the composer command

### Possible solution
Adding support to composer 2 in the composer.json or creating a branch for composer 2

**Comment by jkribeiro** [comment]
This project now supports Composer 2.
