### ISSUE TITLE
Missing robots.txt in the web directory

### ISSUE THREAD

**Issue by brambaud** [drupal-composer/drupal-paranoia#7]
There is no symlink to the `robots.txt` in the web directory.

Is this the wanted behavior? If yes, why?

### Expected behavior

A symlink to the `robots.txt` should exist in the web directory.

### Actual behavior

There is no symlink to the `robots.txt` in the web directory.

### Steps to reproduce

1. Install and configure drupal-paranoia as explained in the [documentation](https://github.com/drupal-composer/drupal-paranoia#configuration) with a based [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project) project.
3. Check the web directory: there is no symlink to the `robots.txt`

### Possible solutions

1. Add the `robots.txt` to the `$assetFileTypes` property of the `\DrupalComposer\DrupalParanoia\Installer` class.
2. Add a configuration option like `drupal-web-dir-extra-asset-files-types` that will be merged with the `$assetFileTypes` property.
3. Dispatch an event at the end of the `\DrupalComposer\DrupalParanoia\Installer::install()` method to let people extend as needed.

IMHO the event dispatcher is the best solution as it will be possible to extend the plugin.

I'll provide a PR when we'll agreed on what to do :)

**Comment by jkribeiro** [comment]
Thanks for reporting this @brambaud.

Yes, I agree, we should add `robots.txt` to the list.

I like to idea to provide an optional composer.json config to extend/merge the list of assets file types and also triggering an event to be able to alter this list.

My suggestion:

- Provide the optional composer.json assets types config: `drupal-asset-files`
- Remove the default value from `$assetFileTypes` property 
- Create a new method `setAssetFileTypes()` that will:
  - Set a default list of files copied from `$assetFileTypes` (include `robots.txt`)
  - Merge `drupal-asset-files` list to the list (if defined)
  - Trigger an event to allow other plugins alter the list of files
  - Remove `.php` values from the list.
  - Set `$assetFileTypes` property value
- Call `setAssetFileTypes()` at `__construct()`
- Update `README` with the new optional config `drupal-asset-files`

Does it make sense? PR is welcome :)
Thanks

**Comment by fancyweb** [comment]
What exactly is the point of moving the default list from the property to the setter please ?

**Comment by jkribeiro** [comment]
Just a thought to encapsulate the merge process (`drupal-asset-files` config) and trigger the event in one method and then every time you need to use the `$assetFileTypes` property you will have the final list.

**Comment by brambaud** [comment]
Thanks for the quick reply! :)

Let's do that!

**Comment by jkribeiro** [comment]
Thanks for your contribution @brambaud.

Released this change to https://github.com/drupal-composer/drupal-paranoia/releases/tag/1.0.0-beta1
