### ISSUE TITLE
Support multisite.

### ISSUE THREAD

**Issue by brambaud** [drupal-composer/drupal-paranoia#9]
Drupal Paranoia does not support multisite.

### Expected behavior

The folder `files` should be symlinked.

```
web/sites
├── site1
│   └── files -> ../../../src/sites/site1/files
├── site2
│   └── files -> ../../../src/sites/site2/files
└── default
    └── files -> ../../../src/sites/default/files
```

### Actual behavior

The folder `files` is not symlinked. But the content is.
So each time you run `composer drupal:paranoia` you lost all your files.

```
web/sites
├── site1
│   └── files
├── site2
│   └── files
└── default
    └── files -> ../../../src/sites/default/files
```
### Steps to reproduce

1. Configure Drupal has a multisite: you can follow https://www.drupal.org/docs/8/multisite
2. Run `composer drupal:paranoia`

### Possible solution

I didn't check for a solution right now but I'll open a PR shortly.

**Comment by jkribeiro** [comment]
This change has been released in `1.0.0-beta2`.

Thanks @brambaud.
